CREATE TABLE [dbo].[CernerPIC_PKList] (
    [DATA_SOURCE]         NVARCHAR (50) NOT NULL,
    [OWNER]               NVARCHAR (50) NOT NULL,
    [CONSTRAINT_NAME]     NVARCHAR (50) NOT NULL,
    [TABLE_NAME]          NVARCHAR (50) NOT NULL,
    [COLUMN_NAME]         NVARCHAR (50) NOT NULL,
    [POSITION]            TINYINT       NULL,
    [CONSTRAINT_TYPE]     NVARCHAR (50) NOT NULL,
    [SEARCH_CONDITION_VC] NVARCHAR (50) NULL
);

