
/*
SELECT * FROM [ctrl].[fnGetEDWSourceObjects] ('EDW')
*/
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE FUNCTION [ctrl].[fnGetEDWSourceObjects] 
(	
	@SourceObjectType varchar(10)='EDW'
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT 
		SourceObjectType, 1 AS BusinessFunctionID, SourceSchema AS TargetFolderName, ''''+SourceSchema+'''' AS TargetFolderNameQuoted, 
		SourceSchema, ''''+SourceSchema+'''' AS SourceSchemaQuoted, 
		SourceObjectName, ''''+SourceObjectName+'''' AS SourceObjectNameQuoted, NULL AS SourceObjectID, SourceObjectName AS TargetObjectName, 
		(CASE SourceObjectType WHEN 'EDW_DIM' THEN 1 ELSE 2 END) AS GroupId,
		'bronze/EDWTEST' LandingPath, NULL AS RawPath, NULL AS StagePath, 'gold/edwtest' AS CuratedPath, 
		1 AS FormatID, 'database' AS FormatName, GETDATE() AS ImportDatetime,
		(CASE SourceObjectType WHEN 'EDW_FCT' THEN BenchMarkField ELSE NULL END) AS BenchMarkField,
		(CASE WHEN SourceObjectType='EDW_FCT' AND SourceObjectName='FCT_CHARGE_TRANSACTION' 			
			THEN 'EXISTS (SELECT 1 FROM  EDW.FCT_ENCOUNTER E WHERE E.SOURCE_ID =EDW.FCT_CHARGE_TRANSACTION.SOURCE_ID AND (CASE WHEN EDW.FCT_CHARGE_TRANSACTION.SOURCE_ID=9 THEN EDW.FCT_CHARGE_TRANSACTION.SOURCE_ENCOUNTER_ID ELSE EDW.FCT_CHARGE_TRANSACTION.SOURCE_PFT_ENCNTR_ID END)=(CASE WHEN E.SOURCE_ID=9 THEN E.SOURCE_ENCOUNTER_ID ELSE E.SOURCE_PFT_ENCNTR_ID END) AND (E.DISCHARGE_DATE_ID >= 20210101 OR E.ADMIT_DATE_ID >= 20210101))'
			WHEN SourceObjectType='EDW_FCT' AND SourceObjectName='FCT_PAYMENT_TRANSACTION' 			
			THEN 'EXISTS (SELECT 1 FROM  EDW.FCT_ENCOUNTER E WHERE E.SOURCE_ID =EDW.FCT_PAYMENT_TRANSACTION.SOURCE_ID AND (CASE WHEN EDW.FCT_PAYMENT_TRANSACTION.SOURCE_ID=9 THEN EDW.FCT_PAYMENT_TRANSACTION.SOURCE_ENCOUNTER_ID ELSE EDW.FCT_PAYMENT_TRANSACTION.SOURCE_PFT_ENCNTR_ID END)=(CASE WHEN E.SOURCE_ID=9 THEN E.SOURCE_ENCOUNTER_ID ELSE E.SOURCE_PFT_ENCNTR_ID END) AND (E.DISCHARGE_DATE_ID >= 20210101 OR E.ADMIT_DATE_ID >= 20210101))'
		ELSE '1=1' END) AS BenchMarkCondition, 
		'ahaidq' AS AdlsContainerName, 'EDWTEST' AS TargetSchema, ROW_NUMBER() OVER(ORDER BY SourceObjectName) AS RowID
	FROM (
		SELECT PARSENAME(col,2) AS SourceSchema, PARSENAME(col,1) AS SourceObjectName, 'EDW_'+LEFT(PARSENAME(col,1),3) AS SourceObjectType,
		(CASE WHEN PARSENAME(col,1)='FCT_ENCOUNTER_CLAIMS' OR PARSENAME(col,1)='FCT_ENCOUNTER' THEN NULL ELSE 'ETL_INSERT_DATE' END) AS BenchMarkField
		FROM (
			SELECT trim(value ) col
			FROM STRING_SPLIT('',',')
			--STRING_SPLIT('EDW.DIM_PERSONNEL,EDW.FCT_ENCOUNTER_PHYSICIAN',',')
			--STRING_SPLIT('EDW.DIM_DATE,EDW.DIM_MEDICAL_SERVICE,EDW.DIM_STATUS,EDW.DIM_FACILITY,EDW.DIM_ERP_PATTYPE_MEDSVC,EDW.DIM_DEPARTMENT,EDW.DIM_PATIENT_TYPE,EDW.DIM_DIAGNOSIS_RELATED_GROUP,EDW.DIM_CHARGE_MASTER,EDW.DIM_PATIENT,EDW.DIM_TRANSACTION_TYPE,EDW.DIM_CPT,EDW.DIM_CARRIER,EDW.FCT_PAYMENT_TRANSACTION,EDW.FCT_ENCOUNTER,EDW.FCT_CHARGE_TRANSACTION,EDW.FCT_ENCOUNTER_CLAIMS',',')
		) T
	) EDWSourceObjects
	WHERE SourceObjectType=(CASE WHEN @SourceObjectType='EDW' THEN SourceObjectType ELSE @SourceObjectType END)
)
GO


